

--Inserts
INSERT INTO TEAM_MEMBER(TEAM_ID, PARTICIPANT_ID) VALUES ();
INSERT INTO PARTICIPANT

--Login
--used for the search
SELECT * FROM USER_ACCOUNT A WHERE A.USERNAME = 'example' AND A.PASSKEY = 'password';
--used to find role
SELECT ROLE_ID FROM USER_ACCOUNT A WHERE A.USERNAME = 'example' AND A.PASSKEY = 'password' ;

--
--FOR DRIVERS
SELECT * FROM USER_ACCOUNT;
SELECT * FROM EVENT;
SELECT * FROM TEAM;
SELECT * FROM TEAM_MEMBER;