--Intializing Schema Written by Chris Godfrey

--There was a little confusion with the data uploading, so I upload little data and made up some participants until I can create a larger data table. I made enough data to test triggers.

--TEST FOR Capacity Trigger

INSERT INTO OLYMPICS(OLYMPIC_ID, OLYMPIC_NUM, HOST_CITY, OPENING_DATE, CLOSING_DATE, OFFICIAL_WEBSITE) VALUES(1, 1, 'London', '27-JUL-12', '12-AUG-12', 'https://www.olympic.org/london-2012'  )

INSERT INTO VENUE(venue_id, olympics_id, venue_name, capacity) VALUES(1, 1, 'Basketball Arena', 2);

INSERT INTO SPORT(SPORT_ID, SPORT_NAME, DESCRIPTION, DOB, TEAM_SIZE) VALUES(1, 'Mens Basketball', 'Basketball played in 4 10 minute quarters.', '07-AUG-36', 5);
INSERT INTO SPORT(SPORT_ID, SPORT_NAME, DESCRIPTION, DOB, TEAM_SIZE) VALUES(2, 'Womens Basketball', 'Basketball played in 4 10 minute quarters.', '07-AUG-36', 5);

INSERT INTO EVENT(EVENT_ID, SPORT_ID, VENUE_ID, GENDER, EVENT_TIME) VALUES(1, 1, 1, 0, '08-AUG-12');
INSERT INTO EVENT(EVENT_ID, SPORT_ID, VENUE_ID, GENDER, EVENT_TIME) VALUES(2, 2, 1, 1, '09-AUG-12');
INSERT INTO EVENT(EVENT_ID, SPORT_ID, VENUE_ID, GENDER, EVENT_TIME) VALUES(3, 1, 1, 0, '10-AUG-12'); --This insert fails as the event capacity is reached

commit;
--Test For Medal Trigger. I'm imagining the events being played by one person at the moment.
INSERT INTO COUNTRY(COUNTRY_ID, COUNTRY, COUNTRY_CODE) VALUES (000, 'USA', 001);
INSERT INTO COUNTRY(COUNTRY_ID, COUNTRY, COUNTRY_CODE) VALUES (001, 'UK', 002);
INSERT INTO COUNTRY(COUNTRY_ID, COUNTRY, COUNTRY_CODE) VALUES (002, 'Germany', 003);
INSERT INTO COUNTRY(COUNTRY_ID, COUNTRY, COUNTRY_CODE) VALUES (003, 'France', 004);
INSERT INTO COUNTRY(COUNTRY_ID, COUNTRY, COUNTRY_CODE) VALUES (004, 'Spain', 005);
INSERT INTO COUNTRY(COUNTRY_ID, COUNTRY, COUNTRY_CODE) VALUES (005, 'Italy', 006);
INSERT INTO COUNTRY(COUNTRY_ID, COUNTRY, COUNTRY_CODE) VALUES (006, 'Greece', 007);

INSERT INTO TEAM(TEAM_ID, OLYMPICS_ID, TEAM_NAME, COUNTRY_ID, SPORT_ID, COACH_ID) VALUES (000, 1, 'US_BASKETBALL' , 000, 1, 0);
INSERT INTO TEAM(TEAM_ID, OLYMPICS_ID, TEAM_NAME, COUNTRY_ID, SPORT_ID, COACH_ID) VALUES (001, 1, 'UK_BASKETBALL' , 001, 1, 1);
INSERT INTO TEAM(TEAM_ID, OLYMPICS_ID, TEAM_NAME, COUNTRY_ID, SPORT_ID, COACH_ID) VALUES (002, 1, 'GERMANY_BASKETBALL' , 002, 1, 2);
INSERT INTO TEAM(TEAM_ID, OLYMPICS_ID, TEAM_NAME, COUNTRY_ID, SPORT_ID, COACH_ID) VALUES (003, 1, 'FRANCE_BASKETBALL' , 003, 1, 3);

INSERT INTO PARTICIPANT(PARTICIPANT_ID, FNAME, LNAME, NATIONALITY, BIRTH_PLACE, DOB) VALUES (0000, 'Chris', 'Godfrey', 'USA', 'USA', '16-DEC-97');
INSERT INTO PARTICIPANT(PARTICIPANT_ID, FNAME, LNAME, NATIONALITY, BIRTH_PLACE, DOB) VALUES (0001, 'John', 'Adam', 'UK', 'USA', '12-DEC-80');
INSERT INTO PARTICIPANT(PARTICIPANT_ID, FNAME, LNAME, NATIONALITY, BIRTH_PLACE, DOB) VALUES (0002, 'Daniel', 'Devito', 'Germany', 'Germany', '10-DEC-77');
INSERT INTO PARTICIPANT(PARTICIPANT_ID, FNAME, LNAME, NATIONALITY, BIRTH_PLACE, DOB) VALUES (0003, 'King', 'Louis', 'France', 'France', '25-DEC-78');

INSERT INTO MEDAL(MEDAL_ID, MEDAL_TITLE, POINTS) VALUES(1, 'gold', 10);
INSERT INTO MEDAL(MEDAL_ID, MEDAL_TITLE, POINTS) VALUES(2, 'silver', 5);
INSERT INTO MEDAL(MEDAL_ID, MEDAL_TITLE, POINTS) VALUES(3, 'bronze', 2);


INSERT INTO SCOREBOARD(OLYMPICS_ID, EVENT_ID, TEAM_ID, PARTICIPANT_ID, POSITION, MEDAL_ID) VALUES (1, 1, 000, 0000, 1, 0);

COMMIT;